FROM bellsoft/liberica-runtime-container:jdk-21-stream-musl AS builder

WORKDIR /app
COPY . .
# Ensure mvnw has executable permissions
RUN chmod +x mvnw

RUN ./mvnw clean package -DskipTests


FROM bellsoft/liberica-runtime-container:jdk-21-stream-musl
COPY --from=builder /app/target/demo-eks-0.0.1-SNAPSHOT.jar demo.jar
ENTRYPOINT ["java", "-jar", "/demo.jar"]